name: Publish to anaconda

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Publish to anaconda
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - name: Conda environment creation
        run: |
          conda env create --file conda_history.yml --name oratio
          conda activate oratio
      - name: Lint with flake8
        run: |
          conda install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Publish to anaconda
        run: conda install conda-build
      - name: List dependencies
        run: conda list
      
